### ISSUE TITLE
add link to deployed site

### ISSUE THREAD

**Issue by pietroppeter** [stegua/coding-math#1]
it can be guessed by assuming you have pages active, but if someone runs in the repo there is not an easy way to see the deployed book.

you could add this in the readme or in repo description (or both): https://stegua.github.io/coding-math/

**Comment by stegua** [comment]
Thanks for your comment. I have added a Readme.md file (at the moment is minimal) and a link in the project description.

If you agree with this solution, I will close the issue.

Ciao!

**Comment by pietroppeter** [comment]
Yep looks good :)
